In [1]:
!python -m pip install --upgrade pip
!python -m pip install numpy

Defaulting to user installation because normal site-packages is not writeable


Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np #np là bí danh (alias) chuẩn được cộng đồng python sử dụng
np.__version__  #kiểm tra version của numpy

'2.3.4'

Vd: Minh hoạ ss kích thước sd bộ nhớ giữa Py List & mảng Numpy array

In [3]:
import numpy as np #import thư viện numpy để tạo và thao tác với mảng Numpy

import sys  #import thư viện sys để đo kích thước của đối tượng Python bằng hàm sys.getsizeof()

#Tạo 1 ds Python List gồm 1000 phần tử
S=list(range(1000))

#Đo kích thước của mỗi phần tử trong ds S
items_S=sys.getsizeof(S)
print("Kích thước mỗi phần tử trong list tính theo byte:",items_S)

#Đo kích thước của toàn bộ ds S
S_size=items_S * len(S)
print("Kích thước toàn bộ list S tính theo byte:",S_size)

#Tạo 1 mảng Numpy array gồm 1000 phần tử
D=np.arange(1000)

#Đo kích thước của mỗi phần tử trong Numpy array
print("Kích thước mỗi phần tử của mảng Numpy array tính theo byte:",D.itemsize)

#Đo kích thước của toàn bộ mảng Numpy array
array_size=D.itemsize * D.size
print("Kích thước toàn bộ mảng Numpy array tính theo byte:",array_size)

print(f"Tỷ lệ (list/array): {S_size/array_size:.2f}")

Kích thước mỗi phần tử trong list tính theo byte: 8056
Kích thước toàn bộ list S tính theo byte: 8056000
Kích thước mỗi phần tử của mảng Numpy array tính theo byte: 8
Kích thước toàn bộ mảng Numpy array tính theo byte: 8000
Tỷ lệ (list/array): 1007.00


In [5]:
# Python code
result = 0
for i in range(100):
    result += i

In [6]:
arr = np.array([1.5, 2.7, 3.2]) #Khởi tạo mảng Numpy array mới (arr)
                                #Do các giá trị đầu vào là số thực, Numpy mặc định gán dtype là float64.
arr

array([1.5, 2.7, 3.2])

In [7]:
#Kiểm tra kiểu dữ liệu các phần tử của arr
arr.dtype

dtype('float64')

In [8]:
#Thực hiện chuyển kiểu dữ liệu
arr_int=arr.astype(np.int32) #Sử dụng phương thức .astype() để tạo một bản sao mới của mảng arr nhưng vs kiểu dữ liệu int32 (số nguyên 32-bit)
print(arr_int, arr_int.dtype)

[1 2 3] int32


In [9]:
print(arr, arr.dtype)

[1.5 2.7 3.2] float64


Vd 3.2.3

In [10]:
import numpy as np

#Kiểu dữ liệu nguyên:
arr_int=np.array([1, 2, 3, 4], dtype=np.int32) #Khởi tạo mảng số nguyên bằng hàm np.array và chỉ định dtype=np.int32
arr_int.dtype

dtype('int32')

In [11]:
print(arr_int)

[1 2 3 4]


In [12]:
print(type(arr_int))

<class 'numpy.ndarray'>


In [13]:
#Kiểu dữ liệu số thực:
arr_float=np.array([1.1 , 2.2, 3.3], dtype=np.float64) #Khởi tạo mảng số thực bằng hàm np.array và chỉ định dtype=np.float64
arr_float.dtype #Output: float64

dtype('float64')

In [15]:
#Kiểu dữ liệu chuỗi (string)::
arr_string = np.array(['apple', 'banana', 'orange'], dtype=np.str_) #Khởi tạo mảng chuỗi bằng hàm np.array và chỉ định dtype=np.string_
arr_string.dtype 

dtype('<U6')

In [16]:
#Kiểu dữ liệu logic (boolean):
arr_bool = np.array([True, False, True], dtype=np.bool_)
arr_bool.dtype # Output: bool

dtype('bool')

Tạo mảng từ danh sách (list) thông qua tự động suy luận kiểu dữ liệu:

In [ ]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
arr_1 = np.array(my_list)
print(arr_1)

[1 2 3 4 5]


In [18]:
arr_1.dtype

dtype('int64')

In [19]:
arr_2 = np.array([my_list], dtype=float)
arr_2

array([[1., 2., 3., 4., 5.]])

In [20]:
arr_2.dtype

dtype('float64')

Tạo mảng 2 chiều:

In [21]:
arr_4=np.array([(1,2,3), (4,5,6)])
arr_4

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a0=np.zeros(5, dtype=int)
a0

array([0, 0, 0, 0, 0])

In [23]:
a0.dtype

dtype('int64')

In [24]:
import numpy as np
# Tạo mảng chứa 5 giá trị từ 0 đến 10 (gồm giá trị kết thúc)
arr_1 = np.linspace(0, 10, 5)
print(arr_1)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# Tạo mảng chứa 10 giá trị từ 0 đến 1 (không chứa giá trị # kết thúc)
arr_2 = np.linspace(0, 1, 10, endpoint=False)
print(arr_2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [26]:
# Tạo mảng chứa 100 giá trị từ 1 đến 10 và trả về kích thước bước.
arr_3, step = np.linspace(1, 10, 100, retstep=True)
print(arr_3)
print("Step size:", step)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [27]:
import numpy as np
# Tạo mảng gồm 5 phần tử từ 0 đến 10 với kiểu dữ liệu là float
arr_4 = np.linspace(0, 10, num=5, dtype=float)
print(arr_4)
print(arr_4.dtype)

[ 0.   2.5  5.   7.5 10. ]
float64


In [28]:
import numpy as np
# Tạo mảng 2 chiều 3x3 gồm các số nguyên ngẫu nhiên từ 0 9
arr_7 = np.random.randint(0,10,(3,3))
print(arr_7)

[[0 0 2]
 [8 0 5]
 [4 4 6]]


In [29]:
import numpy as np
# Tạo mảng 2 chiều 3x3
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
import numpy as np
# Tạo mảng rỗng gồm 5 phần tử, giá trị của 5 phần tử này có thể là bất kỳ giá trị
# nào đã lưu trong bộ nhớ trước đó.
np.empty(5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])

print("Số chiều của mảng là:",arr.ndim)
print("Kích thước của mảng là:",arr.shape)
print("Tổng số phần tử trong mảng là:", arr.size)
print("Kiểu dữ liệu của các phần tử trong mảng là:", arr.dtype)
print("Kích thước theo (byte) của mỗi phần tử trong mảng là:", arr.itemsize)
print("Tổng kích thước theo (byte) của mảng là: ", arr.nbytes)

Số chiều của mảng là: 2
Kích thước của mảng là: (2, 3)
Tổng số phần tử trong mảng là: 6
Kiểu dữ liệu của các phần tử trong mảng là: int64
Kích thước theo (byte) của mỗi phần tử trong mảng là: 8
Tổng kích thước theo (byte) của mảng là:  48


In [32]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]]) #shape = (2,3)

print("Số chiều của mảng là:",arr.ndim)
print("Kích thước của mảng là:",arr.shape)
print("Tổng số phần tử trong mảng là:", arr.size)
print("Kiểu dữ liệu của các phần tử trong mảng là:", arr.dtype)
print("Kích thước theo (byte) của mỗi phần tử trong mảng là:", arr.itemsize)
print("Tổng kích thước theo (byte) của mảng là: ", arr.nbytes)

#BỔ SUNG:
print("Strides (bước nhảy bộ nhớ) là:", arr.strides)

#Ví dụ theo trục (axis):
print("Tổng theo trục 0 (theo cột):", np.sum(arr, axis=0))  #[1+4, 2+5, 3+6]
print("Tổng theo trục 1 (theo hàng):", np.sum(arr, axis=1))  #[1+2+3, 4+5+6]

Số chiều của mảng là: 2
Kích thước của mảng là: (2, 3)
Tổng số phần tử trong mảng là: 6
Kiểu dữ liệu của các phần tử trong mảng là: int64
Kích thước theo (byte) của mỗi phần tử trong mảng là: 8
Tổng kích thước theo (byte) của mảng là:  48
Strides (bước nhảy bộ nhớ) là: (24, 8)
Tổng theo trục 0 (theo cột): [5 7 9]
Tổng theo trục 1 (theo hàng): [ 6 15]


In [36]:
import numpy as np
arr_a = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
#dùng hàm np.sum() và không có 'axis'
np.sum(arr_a)

np.int64(78)

In [34]:
#Dùng hàm np.sum() với 'axis =0'
np.sum(arr_a,axis=0)

array([15, 18, 21, 24])

In [35]:
#Dùng hàm np.sum với 'axis=1'
np.sum(arr_a, axis=1)

array([10, 26, 42])

In [37]:
import numpy as np
A=np.array([1, 2, 3, 4, 5])
A[0] #Phần tử ở vị trí đầu tiên của mảng A

np.int64(1)

In [ ]:
A[4] #Phần tử ở vị trí thứ năm của mảng A

np.int64(5)

In [ ]:
A[-1] #Phần tử ở vị trí cuối cùng của mảng A

np.int64(5)

In [ ]:
A[-2] #Phần tử ở vị trí thứ hai từ cuối mảng

np.int64(4)

In [41]:
import numpy as np
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B[1,2] #Phần tử ở dòng 1, cột 2 của mảng B

np.int64(6)

In [42]:
B[0,0] #Phần tử ở dòng 0, cột 0 của mảng B

np.int64(1)

Kỹ thuật slicing

In [43]:
arr = [0, 1, 2, 3 , 4, 5, 6, 7, 8, 9]
A=np.array(arr)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Lấy i=3 -> A[3:]

In [44]:
A[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [45]:
A[-3:]

array([7, 8, 9])

In [46]:
A[12:]

array([], dtype=int64)

In [48]:
### ***A[i:] <=> A[i::1]***

In [49]:
A[3::1]

array([3, 4, 5, 6, 7, 8, 9])

In [50]:
A[-3::1]

array([7, 8, 9])

In [51]:
A[12::1]

array([], dtype=int64)

### ***A[:i]***

In [52]:
A[:3]

array([0, 1, 2])

In [53]:
A[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [54]:
A[:-12]

array([], dtype=int64)

In [55]:
A[:11]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ví dụ 3.3.2.5

In [1]:
import numpy as np  

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("Cột đầu tiên của mảng arr là: \n", arr[:, 0]) #Lấy all các cột ở vị trí 0
print("Hàng đầu tiên của mảng arr là:", arr[0, :])    #Lấy all các hàng ở vị trí 0
print("Hàng đầu tiên của mảng arr là:", arr[0])       #Cách viết ngắn gọn hơn

Cột đầu tiên của mảng arr là: 
 [1 4 7]
Hàng đầu tiên của mảng arr là: [1 2 3]
Hàng đầu tiên của mảng arr là: [1 2 3]


Vd 3.3.3.1

In [4]:
import numpy as np

# Tạo mảng 2 chiều 3x3
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Sử dụng slicing để tạo view mới từ mảng gốc
arr_view = arr_2d[:2, :2].view() #Tạo view mới từ slicing chỉ chứa 2 dòng và 2 cột của mảng gốc
print(arr_view) #in mảng con arr_con vừa được slicing từ hàm view

[[1 2]
 [4 5]]


In [ ]:
# Thay đổi giá trị trong view
arr_view[0, 0] = 100 #Chỉnh sửa phần tử ở dòng 0, cột 0 thành 100.
print(arr_view) #in ra mảng con sau khi chỉnh sửa.
print(arr_2d) #in mảng gốc để thấy sự thay đổi do view ảnh hưởng đến mảng gốc

[[100   2]
 [  4   5]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [6]:
type(arr_view)

numpy.ndarray

Vd 3.3.3.3

In [7]:
import numpy as np

# Giả sử ta có mảng 2 chiều 3x3 như sau:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_arr_copy = arr_2d[:2, :2].copy()  # Tạo bản sao của mảng con chứa 2 dòng và 2 cột đầu tiên
print(sub_arr_copy)                   # In mảng con vừa sao chép

[[1 2]
 [4 5]]


In [8]:
sub_arr_copy[0, 0] = 10               # Sửa phần tử ở dòng 0, cột 0 của mảng copy thành 10
print(f"Mảng con sau chỉnh sửa:\n{sub_arr_copy}")  # In mảng con sau khi chỉnh sửa

print(f"Mảng gốc:\n{arr_2d}")         # In mảng gốc để thấy mảng gốc không bị ảnh hưởng bởi mảng copy

Mảng con sau chỉnh sửa:
[[10  2]
 [ 4  5]]
Mảng gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


VD 3.3.3.4

In [9]:
import numpy as np

arr = np.arange(1, 10) # Tạo mảng một chiều arr có 9 phần tử từ 1-9
print(f"Mảng 1 chiều ban đầu:\n{arr}")
grid = arr.reshape(3, 3) # Chuyển đổi mảng arr thành mảng grid 3x3

print(f"Mảng 2 chiều sau khi reshape:\n{grid}")


Mảng 1 chiều ban đầu:
[1 2 3 4 5 6 7 8 9]
Mảng 2 chiều sau khi reshape:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Chú ý: reshape() không thay đổi mảng gốc mà tạo ra một mảng mới có hình dạng thay đổi.

Khi muốn chuyển đổi (reshaping) một mảng trong Numpy, kích thước của mảng ban đầu phải khớp với kích thước của mảng định hình lại → tổng số phần tử trong mảng gốc và mảng định hình lại phải giống nhau!

Nếu kích thước khớp nhau → Mảng định hình lại chỉ trỏ đến cùng một vùng nhớ dữ liệu với mảng gốc, mà không tạo ra một bản sao mới.

Trường hợp mảng gốc có bộ nhớ không liên kề (noncontiguous memory), NumPy không thể tạo ra một view (phiên bản không sao chép) và sẽ tạo ra một bản sao mới của mảng.

vd 3.3.3.5

In [10]:
x = np.array([1, 2, 3])      # Tạo mảng một chiều x
x.reshape((1, 3))             # Trả về mảng 2D, nhưng không lưu
# Mã lệnh này không làm thay đổi x – nó chỉ tạo và bỏ đi một bản sao 2D.


array([[1, 2, 3]])

In [11]:
x[np.newaxis, :]  # tạo ma trận hàng (1x3) sd np.newaxis
x

array([1, 2, 3])

Sử dụng np.newaxis()

np.newaxis tương đương với None trong NumPy.

Nó thêm một chiều (axis) mới có kích thước 1 vào vị trí được chỉ định.

Dùng để tăng số chiều của mảng mà không thay đổi dữ liệu.

In [12]:
np.newaxis is None    # Trả về True vì np.newaxis tương đương với None

True

Cú pháp: x[np.newaxis, :]

In [13]:
y = x[np.newaxis, :]   # Thêm một hàng kích thước 1 vào ma trận x
print(f'Ma trận x ban đầu:', x)
print(f'Ma trận y sau khi thêm hàng:', y)


Ma trận x ban đầu: [1 2 3]
Ma trận y sau khi thêm hàng: [[1 2 3]]


Cú pháp: x[: ,np.newaxis]

In [14]:
z = x[:, np.newaxis]   # Thêm một cột kích thước 1 vào ma trận x
print(f'Ma trận x ban đầu:', x)
print(f'Ma trận z sau khi thêm cột:\n', z)


Ma trận x ban đầu: [1 2 3]
Ma trận z sau khi thêm cột:
 [[1]
 [2]
 [3]]


In [15]:
#Giả sử x có shape (3,) -> 1 chiều
x

array([1, 2, 3])

In [16]:
x[np.newaxis, :]  # lấy toàn bộ cột 0, thêm 1 chiều mới ở vị trí đầu tiên (vị trí 0) để tạo ma trận hàng (1-3)
x

array([1, 2, 3])

In [17]:
x.reshape((3,1)) #tạo ma trận cột (3x1) từ mảng 1 chiều x

array([[1],
       [2],
       [3]])

In [18]:
np.ndim(x) #ktra số chiều của mảng x sau khi reshape

1

In [19]:
np.ndim(x.reshape(3,1))

2

3.3.4. Kết hợp, chia tách mảng
a. Kết hợp mảng – Array Concatenation

Hàm: np.concatenate()

Cú pháp:

numpy.concatenate((a1, a2, ...), axis=0, out=None)


Trong đó:

*a1, a2, ... : là các mảng đầu vào

*axis=0 : mặc định nối theo trục 0 (chiều dọc) / theo hàng

*out=None : mặc định, nếu không được chỉ định, một mảng mới được tạo ra để lưu kết quả

vd 3.3.4.1

In [20]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Nối hai mảng x và y theo trục 0 (mặc định) theo hàng để tạo mảng một chiều mới
np.concatenate(([x, y]))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate([x, y], axis=1) # Lỗi vì mảng x và y là mảng 1 chiều, không có trục 1 để nối theo cột.

AxisError: axis 1 is out of bounds for array of dimension 1

In [22]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

# Nối mảng a và b theo trục 0 (hàng) để tạo mảng mới 4×2
np.concatenate([a, b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
np.concatenate([a,b], axis=1) #Nối mảng a và b theo tục 1 (cột) để tạo mảng mới 2x4

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Hàm np.vstack(): "vertical stack" = ghép dọc (theo hàng)

Cú pháp:

numpy.vstack(tup)


Trong đó:

tup là một tuple chứa các mảng đầu vào cần được xếp chồng theo chiều dọc(theo hàng) (trục 0).

Chức năng:
 Ghép nhiều mảng lại với nhau theo CHIỀU DỌC → thêm hàng mới.

Lưu ý:

Tất cả các mảng phải có cùng số cột.

vd 3.3.4.2

In [24]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
c=np.vstack([a,b])  #Ghép mảng a & b theo hàng (trục axis=0) để tạo mảng mới 4x2
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
#vd 3.4.1
import numpy as np
import time

# Tạo một mảng NumPy với 100.000.000 phần tử
arr = np.arange(100000000, dtype=np.int64)

# Tính tổng các phần tử của mảng bằng vòng lặp
start_time = time.time()

total = np.int64(0)
for num in arr:
    total += num

end_time = time.time()
elapsed_time_loop = end_time - start_time

print("Tổng các phần tử mảng arr khi sử dụng vòng lặp:", total)
print("Thời gian (giây) khi sử dụng vòng lặp:", elapsed_time_loop)

# Tính tổng các phần tử của mảng bằng np.sum()
start_time = time.time()

total = np.sum(arr)

end_time = time.time()
elapsed_time_npsum = end_time - start_time

print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum():", total)
print("Thời gian (giây) khi sử dụng np.sum():", elapsed_time_npsum)

num_times_faster = elapsed_time_loop / elapsed_time_npsum
print("Sử dụng vòng lặp chậm hơn: ~",int(num_times_faster),"lần")

Tổng các phần tử mảng arr khi sử dụng vòng lặp: 4999999950000000
Thời gian (giây) khi sử dụng vòng lặp: 11.184544086456299
Tổng các phần tử mảng arr khi sử dụng hàm np.sum(): 4999999950000000
Thời gian (giây) khi sử dụng np.sum(): 0.06217694282531738
Sử dụng vòng lặp chậm hơn: ~ 179 lần


vd3.4.2

In [26]:
import numpy as np
import timeit # Import thư viện timeit để đo thời gian thực thi của các đoạn code.

# Tính tổng của mảng sử dụng Numpy
np_setup = "import numpy as np; np_array = np.arange(1, 1000001)"
np_code = "np_sum = np.sum(np_array)"
np_time = timeit.timeit(stmt=np_code, setup=np_setup, number=10)

# Tính tổng của danh sách sử dụng List
list_setup = "list_array = list(range(1, 1000001))"
list_code = "list_sum = sum(list_array)"
list_time = timeit.timeit(stmt=list_code, setup=list_setup,
number=10)

print("Thời gian tính toán của Numpy:", np_time)
print("Thời gian tính toán của List:", list_time)

print("Numpy tính nhanh hơn List ở lượt chạy là ~ ", int(list_time/np_time), "lần!!")

Thời gian tính toán của Numpy: 0.006694000214338303
Thời gian tính toán của List: 0.06220420077443123
Numpy tính nhanh hơn List ở lượt chạy là ~  9 lần!!
