In [1]:
import numpy as np

In [2]:
# Bước 1: Tạo array arr 3x3 với giá trị True
arr = np.full((3, 3), True)
print("Bước 1: arr 3x3 với True:\n", arr)

Bước 1: arr 3x3 với True:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
# Bước 2: Tạo arr_ID và reshape thành 2D 3x3
arr_ID = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_ID.reshape(3, 3)
# Đổi cột 1 <-> cột 3
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\nBước 2: Đổi cột 1 <-> cột 3:\n", arr_2D)


Bước 2: Đổi cột 1 <-> cột 3:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [4]:
# Bước 3: Đổi dòng 1 <-> dòng 2
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("\nBước 3: Đổi dòng 1 <-> dòng 2:\n", arr_2D)


Bước 3: Đổi dòng 1 <-> dòng 2:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]


In [5]:
# Bước 4: Đảo ngược các dòng
arr_2D = arr_2D[::-1, :]
print("\nBước 4: Đảo ngược các dòng:\n", arr_2D)


Bước 4: Đảo ngược các dòng:
 [[8 7 6]
 [2 1 0]
 [5 4 3]]


In [6]:
# Bước 5: Đảo ngược các cột
arr_2D = arr_2D[:, ::-1]
print("\nBước 5: Đảo ngược các cột:\n", arr_2D)



Bước 5: Đảo ngược các cột:
 [[6 7 8]
 [0 1 2]
 [3 4 5]]


In [7]:
# Bước 6: Kiểm tra giá trị null trong array
arr_2D_null = np.array([
    [1, 2, 3, np.nan],
    [5, 6, 7, np.nan],
    [8, 9, np.nan, 10]
])
has_null = np.isnan(arr_2D_null).any()
print("\nBước 6: Có giá trị null không?", has_null)



Bước 6: Có giá trị null không? True


In [8]:
# Bước 7: Thay thế giá trị null bằng 0
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\nBước 7: Thay null bằng 0:\n", arr_2D_null)


Bước 7: Thay null bằng 0:
 [[ 1.  2.  3.  0.]
 [ 5.  6.  7.  0.]
 [ 8.  9.  0. 10.]]
