Ví dụ 4.5.1.1.a

In [ ]:
#Series đơn giản vs index tuy chỉnh
sr_simple = pd.Series([1, 2, 3], index=['a', 'b', 'c'])

#Áp dụng ufunc unary
print("Series gốc: \n", sr_simple)
print("\nSeries sau khi áp dụng np.sqrt: \n", np.sqrt(sr_simple))

Vd 4.5.1.2.a

In [5]:
import pandas as pd
import numpy as np
s1=pd.Series([2,4,6], index=['a','b','c'])
s2=pd.Series([1,3,5], index=['b','c','d'])

In [6]:
s1

a    2
b    4
c    6
dtype: int64

In [7]:
s2

b    1
c    3
d    5
dtype: int64

In [8]:
s1 + s2 #Cộng hai Series với việc căn chỉnh theo index

a    NaN
b    5.0
c    9.0
d    NaN
dtype: float64

In [9]:
s3=pd.Series([2,4,6], index=['a','b','c'])
s4=pd.Series([1,3,5], index=['b','c','d'])

In [10]:
s3

a    2
b    4
c    6
dtype: int64

In [11]:
s4

b    1
c    3
d    5
dtype: int64

In [12]:
s3.add(s4, fill_value=0)  #Phép cộng giữa s3 và s4, với giá trị thiếu được thay thế bằng 0

a    2.0
b    5.0
c    9.0
d    5.0
dtype: float64

Vd 4.5.1.2.b

In [13]:
#Số liệu về top 5 dân số tỉnh/thành Việt Nam thiếu 1 số tỉnh trg top 5 diện tích
population = pd.Series({'TP.Hồ Chí Minh': 8993082,
                        'Hà Nội': 8330000,
                        'Thanh Hoá': 3720000,
                        'Nghệ An': 341000,
                        'Đồng Nai': 3097107})

#Số liệu về top 5 diện tích 1 số tỉnh/thành Việt Nam, thiếu 1 số tỉnh trg top 5 dân số
area = pd.Series({'Nghệ An': 16493.8,
                  'Gia Lai': 15536.9,
                  'Sơn La': 14174.4,
                  'Đăk Lăk': 13030.5,
                  'Thanh Hoá': 11132.2})

print("Top 5 tỉnh/thành đông dân nhất Việt Nam 2023:\n", population)
print("Top 5 tỉnh/thành có diện tích lớn nhất Việt Nam 2023:\n", area)

Top 5 tỉnh/thành đông dân nhất Việt Nam 2023:
 TP.Hồ Chí Minh    8993082
Hà Nội            8330000
Thanh Hoá         3720000
Nghệ An            341000
Đồng Nai          3097107
dtype: int64
Top 5 tỉnh/thành có diện tích lớn nhất Việt Nam 2023:
 Nghệ An      16493.8
Gia Lai      15536.9
Sơn La       14174.4
Đăk Lăk      13030.5
Thanh Hoá    11132.2
dtype: float64


In [14]:
#Tính mật độ dân số từ 2 Series area và population
desity = area[:5]/population[:5]

print("Mật độ dân số của các tỉnh/thành:\n", desity)


Mật độ dân số của các tỉnh/thành:
 Gia Lai                NaN
Hà Nội                 NaN
Nghệ An           0.048369
Sơn La                 NaN
TP.Hồ Chí Minh         NaN
Thanh Hoá         0.002993
Đăk Lăk                NaN
Đồng Nai               NaN
dtype: float64


In [15]:
#Kiểm tra thứ tự index
print("Index gốc population:", population.index.tolist())
print("Index kết quả desity:", desity.index.tolist())

Index gốc population: ['TP.Hồ Chí Minh', 'Hà Nội', 'Thanh Hoá', 'Nghệ An', 'Đồng Nai']
Index kết quả desity: ['Gia Lai', 'Hà Nội', 'Nghệ An', 'Sơn La', 'TP.Hồ Chí Minh', 'Thanh Hoá', 'Đăk Lăk', 'Đồng Nai']


In [ ]:
Vd 4.5.1.4

In [16]:
#Tạo 2 DataFrame Adf, Bdf và tìm tổng các giá trị
import pandas as pd
import numpy as np
Adf = pd.DataFrame(np.random.randint(0,10,(2,2)), columns=['A','B'])
Bdf = pd.DataFrame(np.random.randint(0,10,(3,3)), columns=['B','A','C'])

print("Adf:\n", Adf)
print("Bdf:\n", Bdf)

Adf:
    A  B
0  2  8
1  6  9
Bdf:
    B  A  C
0  7  5  7
1  2  9  9
2  6  3  3


In [17]:
Adf + Bdf

A     B   C
0   7.0  15.0 NaN
1  15.0  11.0 NaN
2   NaN   NaN NaN

Vd 4.5.1.5

In [18]:
A=pd.DataFrame(np.arange(9.).reshape(3,3), columns=list('ABC')) #Khởi tạo DataFrame A vs 3 cột A,B,C
B=pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('ABC')) #Khởi tạo DataFrame B vs 3 cột A,B,C

In [19]:
A

A    B    C
0  0.0  1.0  2.0
1  3.0  4.0  5.0
2  6.0  7.0  8.0

In [20]:
B

A     B     C
0  0.0   1.0   2.0
1  3.0   4.0   5.0
2  6.0   7.0   8.0
3  9.0  10.0  11.0

In [21]:
A+B

A     B     C
0   0.0   2.0   4.0
1   6.0   8.0  10.0
2  12.0  14.0  16.0
3   NaN   NaN   NaN

Vd 4.5.2.1

In [22]:
#CỐ ĐỊNH KẾT QUẢ ĐỂ DỄ THEO DÕI
np.random.seed(0) #Quan trọng: kết quả thông dịch sẽ giống nhau 

#Tạo 1 mảng Numpy 2 chiều 3x4 từ 10 phần tử ngẫu nhiên 0-9
arr = np.random.randint(10, size=(3, 4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [23]:
arr[0]

array([5, 0, 3, 3], dtype=int32)

In [24]:
arr-arr[0] #Trừ mỗi hàng trong mảng arr cho hàng đầu tiên của chính nó -> Numpy broadcasting theo hàng

array([[ 0,  0,  0,  0],
       [ 2,  9,  0,  2],
       [-3,  4,  4,  3]], dtype=int32)

Vd trg Pandas

In [26]:
#Tạo DataFrame df từ mảng Numpy arr, vs các cột đặt tên là P,Q,M,N
df = pd.DataFrame(arr, columns=['P', 'Q', 'M', 'N'])
print("DataFrame df:\n", df)

DataFrame df:
    P  Q  M  N
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6


In [28]:
df.iloc[0] #Lấy hàng đầu tiên của DataFrame df dưới dạng Series

P    5
Q    0
M    3
N    3
Name: 0, dtype: int32

In [29]:
df.iloc[0].index #Index của Series lấy từ hàng đầu tiên của DataFrame df

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [30]:
df.columns

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [31]:
df.iloc[0].index=df.columns #Kiểm tra sự trùng khớp giữa index của Series và columns của DataFrame

In [32]:
df.iloc[0].name

0

In [33]:
df

P  Q  M  N
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6

Vd 4.5.2.2

In [35]:
df['Q'] #Lấy cột Q từ DataFrame df dưới dạng Series

0    0
1    9
2    4
Name: Q, dtype: int32

In [36]:
#Trừ các phần tử trg DataFrame df cho các phần tử trg Series lấy từ cột Q
print('df1:\n', df.subtract(df['Q'], axis=0)) #axis=0 sd để căn chỉnh hàng của DataFrame df với index của Series df['Q']

df1:
    P  Q  M  N
0  5  0  3  3
1 -2  0 -6 -4
2 -2  0  3  2


In [37]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [38]:
df['Q'].index=df.index #Kiểm tra sự trùng khớp giữa index của Series lấy từ cột Q và index của DataFrame df

In [39]:
#Nhân các phần tử tương ứng của df vs cột 'N'
print('df2:\n', df.multiply(df['N'], axis=0)) #axis=0 sd để căn chỉnh hàng của DataFrame df với index của Series df['N']

df2:
     P   Q   M   N
0  15   0   9   9
1  35  45  15  25
2  12  24  42  36


In [40]:
#Muốn giống Numpy? Tạo series vs index = hàng
import pandas as pd
row_series = pd.Series([5,0,3,3], index=[0,1,2,3])

In [41]:
row_series

0    5
1    0
2    3
3    3
dtype: int64

Vd 4.5.3.1

In [42]:
import numpy as np
import pandas as pd

#1. None khiến dtype chuyển thành object
arr_none = np.array([1, 2, None, 3])
print("1. Mảng có None (dtype=object):")
print(arr_none)

1. Mảng có None (dtype=object):
[1 2 None 3]


In [43]:
type(arr_none)

numpy.ndarray

In [44]:
#2. Minh hoạ lỗi phép toán
print("\n2. Lỗi khi tính mean() trên mảng object chứa None:")
try: 
    #Phép toán số học k thực hiện đc trên object chứa None
    arr_none.mean()
except TypeError as e:
    print("Lỗi:", e)


2. Lỗi khi tính mean() trên mảng object chứa None:
Lỗi: unsupported operand type(s) for +: 'int' and 'NoneType'


In [45]:
print("\n3. Minh hoạ lỗi khi tính sum() trên object thuần:")
ar_pure_obj = np.array([1, 2, 3, 4], dtype=object)
try:
    #Ngay cả khi không có None, phép toán số học vẫn k thực hiện đc trên object thuần
    ar_pure_obj.sum()
except TypeError as e:
    print(f" -> Lỗi: {e} (do có chuỗi '4')")


3. Minh hoạ lỗi khi tính sum() trên object thuần:


In [46]:
#3. So sánh tốc độ tính toán giữa mảng dtype object và int
for dtype in ['object', 'int']:
    print("dtype:", dtype)
    %timeit np.arange(1e6, dtype=dtype).sum()
    print()

dtype: object
280 ms ± 91.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

dtype: int
The slowest run took 6.79 times longer than the fastest. This could mean that an intermediate result is being cached.
15.8 ms ± 11.8 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)



Vd 4.5.3.2

In [47]:
#Minh hoạ NaN
arr_nan = np.array([1, np.nan, 3, 4])
print(f"Mảng gốc: {arr_nan}")

Mảng gốc: [ 1. nan  3.  4.]


In [48]:
#Tính chất NaN
arr_nan.sum(), arr_nan.min(), arr_nan.max()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [49]:
#Giải pháp nansum()
np.nansum(arr_nan), np.nanmin(arr_nan), np.nanmax(arr_nan)

(np.float64(8.0), np.float64(1.0), np.float64(4.0))

Vd 4.5.3.3

In [50]:
import pandas as pd
sr_auto = pd.Series([1, 2, np.nan, 4, None])
sr_auto

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [51]:
print(f"Dtype sau chuyển đổi: {sr_auto.dtype}")

Dtype sau chuyển đổi: float64


In [52]:
sr_int_na = pd.Series([1, 2, None, 4], dtype=pd.Int64Dtype())
print(f"Series giữ Int: \n{sr_int_na}")
print(f"Dtype sau: {sr_int_na.dtype}")

Series giữ Int: 
0       1
1       2
2    <NA>
3       4
dtype: Int64
Dtype sau: Int64


In [53]:
st_sr=pd.Series(['Uneti', 'Khưd', None, np.nan])
st_sr

0    Uneti
1     Khưd
2     None
3      NaN
dtype: object

Vd 4.5.3.6

vd 4.5.3.8

In [54]:
data = pd.Series

In [ ]:
df_demo

In [ ]:
df_filled = df_demo.fillna(0) #Thay thế all giá trị NaN bằng 0
df

In [ ]:
print("--- 9. Demo fillna bằng giá trị Thống kê ---")
print(f"DataFrame gốc:\n{df_demo}")

# Thay thế NA trong cột 'A' bằng giá trị trung bình (mean) của chính cột đó
mean_A = df_demo['A'].mean()
df_fill_mean = df_demo.fillna({'A': mean_A})

print(f"Giá trị trung bình của cột A: {mean_A:.2f}")
print(f"Kết quả fillna bằng mean của A:\n{df_fill_mean}")

 vd 4.5.3.9

In [58]:
print("-12. Chuẩn bị DataFrame có Outlies cho Demo---")

-12. Chuẩn bị DataFrame có Outlies cho Demo---


In [57]:
import pandas as pd

# #1. Định nghĩa Tuple đại diện cho tỉnh/TP - Năm tương ứng
index_tuples = [
    ('Hà Nội', 2015), ('Hà Nội', 2020),
    ('Nam Định', 2015), ('Nam Định', 2020),
    ('Thanh Hóa', 2015), ('Thanh Hóa', 2020),
    ('Đà Nẵng', 2015), ('Đà Nẵng', 2020),
    ('Hồ Chí Minh', 2015), ('Hồ Chí Minh', 2020)
]

# #2. Dữ liệu (Sử dụng nguồn dữ liệu chính xác đã thống nhất)
data = [
    7216000, 8246540,
    1850600, 1780330,
    3514200, 3664940,
    1028800, 1169480,
    8146300, 9227600
]

# Sau bước này, bạn sẽ tạo Series hoặc DataFrame bằng cách sử dụng
# index=index_tuples và data=data, ví dụ:
# vn_pop_2015_2020 = pd.Series(data=data, index=index_tuples)

# 3. Tạo Series (CHỈ SỬ DỤNG TUPLE INDEX)
vn_pop = pd.Series(data=data, index=index_tuples)

print("Series sử dụng Index bằng Tuple (Cách thủ công):")
vn_pop
# Khi chạy trong môi trường như Jupyter/Colab, chỉ cần gọi tên biến 'vn_pop' để hiển thị
# Nếu chạy trong môi trường console, bạn có thể dùng print(vn_pop)

Series sử dụng Index bằng Tuple (Cách thủ công):


(Hà Nội, 2015)         7216000
(Hà Nội, 2020)         8246540
(Nam Định, 2015)       1850600
(Nam Định, 2020)       1780330
(Thanh Hóa, 2015)      3514200
(Thanh Hóa, 2020)      3664940
(Đà Nẵng, 2015)        1028800
(Đà Nẵng, 2020)        1169480
(Hồ Chí Minh, 2015)    8146300
(Hồ Chí Minh, 2020)    9227600
dtype: int64

In [ ]:
# Tạo MultiIndex cho HÀNG (row index)
index = pd.MultiIndex.from_product([[2020, 2021, 2022], [1, 2, 3]],
                                   names=['Năm', 'Lần thi'])

# Tạo MultiIndex cho CỘT (column index)
columns = pd.MultiIndex.from_product([['Bình', 'Lan', 'Văn'],
                                      ['Toán', 'Lý', 'Hóa']],
                                     names=['Học sinh', 'Môn học'])

# Tạo dữ liệu mẫu, là mảng kích thước 9x9 với các giá trị ngẫu nhiên từ 5-10
data = np.random.randint(5, 10, (9, 9))

# Tạo DataFrame score với dữ liệu ngẫu nhiên từ mảng data kích thước 9x9 trong đó các chỉ mục hàng và cột được thiết lập
score = pd.DataFrame(data=data, index=index, columns=columns)

# Hiển thị DataFrame
score